const vetorfonemas = [
  "AR - ER - IR - OR - UR",
  "ARRA - ERRE - IRRI - ORRO - URRU",
  "ARA - ERE - IRI - ORO - URU",
  "PRA - PRE - PRI - PRO - PRU",
  "DRA - DRE - DRI - DRO - DRU",
  "BRA - BRE - BRI - BRO - BRU",
  "VRA - VRE - VRI - VRO - VRU",
  "AS - ES - IS - OS - US",
  "ASSA - ESSE - ISSI - OSSO - USSU",
  "ASA - ESE - ISI - OSO - USU",
  "LHA - LHE - LHI - LHO - LHU",
  "CHA - CHE - CHI - CHO - CHU",
  "NHA - NHE - NHI - NHO - NHU",
  "GUE - GUI",
  "QUE - QUI",
  "BAN - BEN - BIN - BON - BUN",
  "VAM - VEM - VIM - VOM - VUM",
];
export default vetorfonemas;
