// esses fonemas são avançados, pro Leonardo.
// const vetorfonemas = [
//   "AR - ER - IR - OR - UR",
//   "ARRA - ERRE - IRRI - ORRO - URRU",
//   "ARA - ERE - IRI - ORO - URU",
//   "PRA - PRE - PRI - PRO - PRU",
//   "DRA - DRE - DRI - DRO - DRU",
//   "BRA - BRE - BRI - BRO - BRU",
//   "VRA - VRE - VRI - VRO - VRU",
//   "AS - ES - IS - OS - US",
//   "ASSA - ESSE - ISSI - OSSO - USSU",
//   "ASA - ESE - ISI - OSO - USU",
//   "LHA - LHE - LHI - LHO - LHU",
//   "CHA - CHE - CHI - CHO - CHU",
//   "NHA - NHE - NHI - NHO - NHU",
//   "GUE - GUI",
//   "QUE - QUI",
//   "BAN - BEN - BIN - BON - BUN",
//   "VAM - VEM - VIM - VOM - VUM",
//   "BAM - BEM - BIM - BOM - BUM",
//   "PAR - PER - PIR - POR - PUR",
//   "RA - RE - RI - RO - RU",
//   "SA - SE - SI - SO - SU"
// ];

//fonemas pra clara
const vetorfonemas = [
  "BA - BE - BI - BO - BU",
  "CA - CE - CI - CO - CU",
  "DA - DE - DI - DO - DU",
  "FA - FE - FI - FO - FU",
  'GA - GE - GI - GO - GU',
  "JA - JE - JI - JO - JU",
  "LA - LE - LI - LO - LU",
  "MA - ME - MI - MO - MU",
  "NA - NE - NI - NO - NU",
  "PA - PE - PI - PO - PU",
  "RA - RE - RI - RO - RU",
  "SA - SE - SI - SO - SU",
  "TA - TE - TI - TO - TU",
  "VA - VE - VI - VO - VU",
  'XA - XE - XI - XO - XU',
  "ZA - ZE - ZI - ZO - ZU",
  "AR - ER - IR - OR - UR",
  "AS - ES - IS - OS - US",
  "GUE - GUI",
  "QUE - QUI",
  "BRA - BRE - BRI - BRO - BRU",
  "CRA - CRE - CRI - CRO - CRU",
  "PRA - PRE - PRI - PRO - PRU",
  "GRA - GRE - GRI - GRO - GRU",
  "FRA - FRE - FRI - FRO - FRU",
  "TRA - TRE - TRI - TRO - TRU",
  "VRA - VRE - VRI - VRO - VRU",
  "BLA - BLE - BLI - BLO - BLU",
  "CLA - CLE - CLI - CLO - CLU",
  "PLA - PLE - PLI - PLO - PLU",
  "GLA - GLE - GLI - GLO - GLU",
  "FLA - FLE - FLI - FLO - FLU",
  ]
export default vetorfonemas;
